import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Container, Paper, Typography, styled, TextField, FormControl, InputLabel, Select, MenuItem } from '@mui/material'
import axiosClient from '../functions/fetch'
import { useEffect, useState } from 'react'
import { AxiosResponse } from 'axios'

const inter = Inter({ subsets: ['latin'] })

const ContentWrapper = styled(Paper)({
  backdropColor: '#fff',
  width: '100%',
  maxWidth: 800,
  minHeight: '80vh',
  padding: 20,
  margin: '0 auto',
})

const Title = styled('h1')({
  textAlign: 'center'
})

export default function Home() {
  const user = '999084@tci'

  useEffect(() => {
    try {
      //ユーザデータ
      axiosClient.get(`/user?account=${user}`)
      .then((res: AxiosResponse) => {
        const accountId = res.data[0].accountId
        const coinBalance = res.data[1][0].balance
        const userData = JSON.parse(res.data[0].jsonData)[accountId]
        setId(accountId)
        setCoinBalance(coinBalance)
        setName(userData.name)
        setEmail(userData.email)
        console.log(res.data)
      })
      .catch((err) => {
        throw err
      })

      //コイン情報
      axiosClient.get(`/tx?account=${user}`)
      .then((res: AxiosResponse) => {
        console.log(res.data[0])
        setTransactions(res.data[0].transactionList)
      })
      .catch((err) => {
        throw err
      })

    } catch (err) {
      alert(`データ読み込み失敗: ${err}`)
    }
  }, [])

  const [id, setId] = useState('')
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [coinBalance, setCoinBalance] = useState(0)
  const [transactions, setTransactions] = useState([])

  return (
    <>
      <Head>
        <title>home | wancoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <ContentWrapper>
            <Title>ようこそ、{name}さん</Title>
            <h2>ユーザー情報</h2>
            <Typography>ユーザID: {id.split('@')[0]}</Typography>
            <Typography>Eメール: {email}</Typography>
            <Typography>コイン: {Number(coinBalance).toLocaleString()}</Typography>
            <Typography>もらったコイン: yyy</Typography>
            <Typography>あげたコイン: xxx</Typography>
            <h2>やり取り履歴</h2>
            <div>
              {/* {transactions.map((tx, i) => {
                return (<p key={i}>{i}</p>)
              })} */}
            <ul>
              <li>テスト</li>
              <li>テスト02</li>
              <li>テスト03</li>
            </ul>
            </div>
            <h2>コインを送る</h2>
            <TextField id="to" label="Filled" variant="filled" />
            <FormControl>
              <InputLabel id="">Age</InputLabel>
              <Select labelId="" id="" // value={age} label="Age" onChange={handleChange} >]
              >
                <MenuItem value="#感謝">#感謝</MenuItem>
                <MenuItem value="#DMマフィア">#DMマフィア</MenuItem>
                <MenuItem value="#Our Styles">#Our Styles</MenuItem>
              </Select>
            </FormControl>
            <TextField id="message" label="Filled" variant="filled" />
            <TextField id="amount" label="Filled" variant="filled" />
          </ContentWrapper>
        </Container>
      </main>
    </>
  )
}
